var library = [{ author: 'Bill Gates', title: 'The Road Ahead', readingStatus: true }, { author: 'Steve Jobs', title: 'Walter Isaacson', readingStatus: true }, { author: 'Suzanne Collins', title: 'Mockingjay: The Final Book of The Hunger Games', readingStatus: false }];
for (item of library) {
    console.log(item.author)
    console.log(item.title)
    console.log(item.readingStatus)
    console.log("------------------------------------------------")
}